### ISSUE TITLE
Fatal error: Class 'React\EventLoop\Factory' not found

### ISSUE THREAD

**Issue by tech4syssoftware** [reactphp/reactphp#306]
I just downloaded the reactphp code from git and  used composer to install. Installation done successfully, but facing below issue when I browse any file in examples. 

Fatal error: Class 'React\EventLoop\Factory' not found.

I am running this in WIndows.
Please help me in this regard.

**Comment by rjrincon** [comment]
when I try to run the following command: ./Console/cake Ratchet.websocket start --verbose

Fatal error: Class 'React\EventLoop\Factory' not found in C:\wamp\www\project\app\Plugin\Ratchet\Console\Command\WebsocketShell.php on line 51

**Comment by clue** [comment]
Hi @rjrincon, are you sure this is an issue in react/react? `cake` and `Ratchet.websocket` seem to indicate otherwise. You may want to check the installation instructions of your environment, perhaps you've missed to run `composer install`?

**Comment by Mokshes** [comment]
Class 'ReactEventLoopFactory' not found 
I have reinstall the composer but it is still giving me this error 
Can Any one help ?

**Comment by clue** [comment]
@Mokshes Can you show a gist of your code and the commands you've executed to install and run this?

The fully-qualified name for this class should be `React\EventLoop\Factory`. Also make sure to actually load the Composer autoloader via `require __DIR__ . '/vendor/autoload.php';` before using any of the classes.

I hope this helps :+1:

**Comment by Mokshes** [comment]
I have done this and install the things 
Thank You @clue

**Comment by Mokshes** [comment]
👍

**Comment by brunoromeo001** [comment]
Hello the file class Factory not exists on my folder src, how can i download him?

**Comment by clue** [comment]
@brunoromeo001 You need to install the [EventLoop component](https://reactphp.org/event-loop/) like this:

```bash
$ composer install react/event-loop
```
