### ISSUE TITLE
Uncaught RuntimeException: Failed to listen on reactphp

### ISSUE THREAD

**Issue by kamyabsoft** [reactphp/reactphp#437]
hi
When I upload the following code in my vps, I get the following error.
`require_once 'vendor/autoload.php';
use React\Http\Server;
use React\Http\Response;
use React\EventLoop\Factory;
use Psr\Http\Message\ServerRequestInterface;

// init the event loop
$loop = Factory::create();

// set up the components
$server = new Server(function (ServerRequestInterface $request) {
return new Response(200, ['Content-Type' => 'text/plain'],  "Hello world\n");
});

$socket = new \React\Socket\Server('127.0.0.1:8080', $loop);
$server->listen($socket);

// run the application
$loop->run();`

It runs on xampp without any problems, but it gives the following error on the server
`Fatal error: Uncaught RuntimeException: Failed to listen on "tcp://127.0.0.1:8080": Address already in use in /usr/local/apache/htdocs/vendor/react/socket/src/TcpServer.php:164 Stack trace: #0 /usr/local/apache/htdocs/vendor/react/socket/src/Server.php(36): React\Socket\TcpServer->__construct('tcp://127.0.0.1...', Object(React\EventLoop\StreamSelectLoop), Array) #1 /usr/local/apache/htdocs/index.php(19): React\Socket\Server->__construct(8080, Object(React\EventLoop\StreamSelectLoop)) #2 {main} thrown in /usr/local/apache/htdocs/vendor/react/socket/src/TcpServer.php on line 164`

When I enter the site address, it goes to the infinite load for the first time. I click the same address again. The error is displayed. I even changed the port, but it didn't make a difference

**Comment by clue** [comment]
Hey @kamyabsoft, welcome to ReactPHP! 👋

> Failed to listen on "tcp://127.0.0.1:8080": Address already in use

This indicates some other process is already listening on this address (like some other Apache or nginx process). This means that ReactPHP was unable to listen on this address. Accordingly, trying to connect to this address will actually connect to that other process instead of ReactPHP.

You can try another port number or use the special port `0` to automatically assign a random free port. You can then use `$socket->getAddress()` to get the assigned address.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

**Comment by kamyabsoft** [comment]
Thanks for your guidance
It no longer displays errors
But the site goes on the infinite load and not echo hello world
And every time the address is loaded, it is added to a new process in ssh, why ??

**Comment by kamyabsoft** [comment]
my website address : http://103.215.221.123/ 
please check it .
tnx

**Comment by kamyabsoft** [comment]
Thanks for your guidance
The method $socket->getAddress() show me free port 37423 and i us this port in my code
But again, the loading of the site was infinite for the first time. I clicked on the site address again and it gave the same error as above and not echo hello world
my adress : http://103.215.221.123/

**Comment by clue** [comment]
You will need to change to your listening address to your public IP or the special address `0.0.0.0:0` to listen on a random port on all interfaces. It may always assign a different port, but in your example you should be able to send a request to `http://103.215.221.123:37423/`.

Also, are you running this example from the command line? Note that this should not be embedded into a "normal" PHP script using a traditional SAPI like Apache/nginx. The script will keep running *forever* and you should be able to connect to it as long as the process is running. You may also have to check your firewall settings if external connections are somehow restricted.

**Comment by kamyabsoft** [comment]
Thank you very much for solving my problem .
with my isp My site address is easily loaded and shows the text Hello World
but for my friends ( check with two different isp ) my page not load . do you know why ?
website : http://103.215.221.123:37423/

**Comment by clue** [comment]
@kamyabsoft Happy to hear you're making some progress.

The remaining problem you're describing sounds more like a firewall issue than a problem with ReactPHP. To isolate this issue, you may also try running another server process such as `nc -l 0.0.0.0 37423` and see if a connection can be established.
