### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by Lucas-Ayabe** [reactphp/reactphp#441]
I tried to create hello world as indicated in some documentation sources (the first documentation code and the mentioned articles) and both are out of date, the parameters are being passed wrong and the namespaces are incorrect.

**Comment by WyriHaximus** [comment]
The documentation links to the respective components repository readmes, which by default reflect the next release that is worked on. We could consider linking to our website where we host the documentation for the latest releases (and link to all previous version). As for the articles we don't always control them and might be outdated, as such we always recommend using the website for our documentation.

**Comment by clue** [comment]
@Lucas-Ayabe Thanks for reporting, the HTTP example on our homepage has indeed not been updated yet, so I've just filed https://github.com/reactphp/website/pull/52 to address this :+1: 

Other than that, all our components include an examples/ directory that includes a number of up-to-date examples highlighting the most important functionality :+1: 

External articles are not under our control, but we'd also love to see them being updated. If you find an outdated article, make sure to reach out to the respective author, I'm sure most will appreciate a friendly ping.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
