### ISSUE TITLE
Rename `master` branches for ReactPHP projects

### ISSUE THREAD

**Issue by SimonFrings** [reactphp/reactphp#453]
I'm suggesting we rename the `master` branches like already done in [reactphp/async](https://github.com/reactphp/async), [reactphp/filesystem](https://github.com/reactphp/filesystem) and [reactphp/promise](https://github.com/reactphp/promise).

This would be the case for the following projects:

- [x] in [reactphp/cache](https://github.com/reactphp/cache) into `1.x`
- [x] in [reactphp/child-process](https://github.com/reactphp/child-process) into `0.7.x`
- [x] in [reactphp/datagram](https://github.com/reactphp/datagram) into `1.x`
- [x] in [reactphp/dns](https://github.com/reactphp/dns) into `1.x`
- [x] in [reactphp/event-loop](https://github.com/reactphp/event-loop) into `1.x`
- [x] in [reactphp/http](https://github.com/reactphp/http) into `1.x`
- [x] in [reactphp/pomise-stream](https://github.com/reactphp/promise-stream) into `1.x`
- [x] in [reactphp/pomise-timer](https://github.com/reactphp/promise-timer) into `1.x`
- [x] in [reactphp/socket](https://github.com/reactphp/socket) into `1.x`
- [x] in [reactphp/stream](https://github.com/reactphp/stream) into `1.x`

As @clue already described in https://github.com/reactphp/promise/pull/212:

> This has originally been brought up in https://github.com/reactphp/promise/pull/204 by @Seldaek, but instead of defining a branch alias, this PR suggests simply renaming what is currently `master` to `3.x`. This is in line with our existing `2.x` and `1.x` branches and means we do not have to update any alias definitions once we would start working on a potential future `4.x`.

> From a consumer's perspective, this means installation is now much easier, as targeting `^3@dev` (or `3.x-dev`) is semantically more obvious and safer than using `dev-master`. Additionally, keep in mind that branch names are development artifacts that are subject to change at some point in the future. Once we would decide to rename or delete any of our version branches, the `^3@dev` reference would still be valid as it would also match stable versions if we have any `^3` tags at this point (which is safe to assume at this point).

**Comment by clue** [comment]
Agree that this suggestion makes perfect sense and is perfectly in line with what we did in our other components already with https://github.com/reactphp/promise/pull/212, https://github.com/reactphp/async/pull/29, and https://github.com/reactphp/filesystem/pull/101 already :+1: On top of this, this also helps avoid using the loaded `master` wording and not only uses more inclusive wording, but also semantically more meaningful names.

I'm happy to update the branch names if there are no objections :+1:

**Comment by WyriHaximus** [comment]
No objection from me

**Comment by clue** [comment]
Vote results seem to be pretty unanimous so far, I'll give this a couple of days and will update the branch names if there are no objections 👍

**Comment by clue** [comment]
Updated all branch names as suggested :shipit:

I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
